// SPDX-License-Identifier: MPL-2.0
// Copyright (c) grith contributors

//! Shared DNS wire-format parsing for in-line and connected-proxy inspection.
//!
//! Unconnected explicit-destination datagrams remain in-line: the query is
//! parsed from the send buffer and matching responses populate the cache.
//! Feature-gated connected UDP/53 sockets use the same strict parsers in a
//! per-socket managed proxy route so ordinary `write`/`read` calls need not be
//! trapped.
//!
//! Parsing the QNAME closes the DNS exfiltration gap where an attacker encodes
//! secrets in subdomain labels (e.g., `AKIA1234.attacker.com`) and leaks data
//! purely through DNS lookups.

use std::collections::{HashMap, HashSet};
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr};
use std::time::Duration;

/// Parsed metadata for one outbound DNS query.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ParsedQuery {
    pub id: u16,
    pub domain: String,
    pub qtype: u16,
    pub query_type: String,
}

/// One address reached by the response's QNAME/CNAME chain.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct DnsAnswer {
    pub ip: IpAddr,
    pub ttl: Duration,
}

/// A validated DNS response suitable for transaction correlation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ParsedResponse {
    pub id: u16,
    pub domain: String,
    pub qtype: u16,
    pub answers: Vec<DnsAnswer>,
}

/// DNS response codes generated by the connected-UDP inspection proxy.
///
/// Keeping response construction in the wire-format module ensures the
/// in-line and proxy transports do not grow subtly different DNS encoders.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum DnsErrorCode {
    FormErr = 1,
    ServFail = 2,
    Refused = 5,
}

fn read_u16(packet: &[u8], offset: usize) -> Option<u16> {
    let bytes: [u8; 2] = packet.get(offset..offset + 2)?.try_into().ok()?;
    Some(u16::from_be_bytes(bytes))
}

fn read_u32(packet: &[u8], offset: usize) -> Option<u32> {
    let bytes: [u8; 4] = packet.get(offset..offset + 4)?.try_into().ok()?;
    Some(u32::from_be_bytes(bytes))
}

/// Decode a DNS name, including response compression, with cycle and bounds
/// checks. The returned offset is in the original (non-jumped) stream.
fn parse_name(packet: &[u8], start: usize, allow_compression: bool) -> Option<(String, usize)> {
    let mut labels = Vec::new();
    let mut cursor = start;
    let mut resume = None;
    let mut visited = HashSet::new();
    let mut wire_len = 0usize;

    loop {
        if !visited.insert(cursor) || visited.len() > 128 {
            return None;
        }
        let len = *packet.get(cursor)?;
        if len & 0xC0 == 0xC0 {
            if !allow_compression {
                return None;
            }
            let low = *packet.get(cursor + 1)? as usize;
            let target = (((len as usize) & 0x3F) << 8) | low;
            if target >= packet.len() {
                return None;
            }
            resume.get_or_insert(cursor + 2);
            cursor = target;
            continue;
        }
        if len & 0xC0 != 0 {
            return None;
        }
        cursor += 1;
        if len == 0 {
            break;
        }
        let len = len as usize;
        if len > 63 {
            return None;
        }
        let raw = packet.get(cursor..cursor + len)?;
        let label = std::str::from_utf8(raw).ok()?;
        if label.is_empty()
            || !label
                .bytes()
                .all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
        {
            return None;
        }
        wire_len = wire_len.checked_add(len + 1)?;
        if wire_len > 254 {
            return None;
        }
        labels.push(label.to_string());
        cursor += len;
    }

    if labels.is_empty() {
        return None;
    }
    Some((labels.join("."), resume.unwrap_or(cursor)))
}

/// Advance over a DNS name without interpreting its labels.
///
/// Resource-record owner names may legitimately be the root name (notably the
/// EDNS OPT pseudo-record), while QNAMEs used for policy must remain non-empty.
fn skip_name(packet: &[u8], start: usize, allow_compression: bool) -> Option<usize> {
    let mut cursor = start;
    let mut resume = None;
    let mut visited = HashSet::new();

    loop {
        if !visited.insert(cursor) || visited.len() > 128 {
            return None;
        }
        let len = *packet.get(cursor)?;
        if len & 0xC0 == 0xC0 {
            if !allow_compression {
                return None;
            }
            let low = *packet.get(cursor + 1)? as usize;
            let target = (((len as usize) & 0x3F) << 8) | low;
            if target >= packet.len() {
                return None;
            }
            resume.get_or_insert(cursor + 2);
            cursor = target;
            continue;
        }
        if len & 0xC0 != 0 || len > 63 {
            return None;
        }
        cursor += 1;
        if len == 0 {
            return Some(resume.unwrap_or(cursor));
        }
        cursor = cursor.checked_add(len as usize)?;
        packet.get(..cursor)?;
    }
}

fn skip_resource_records(packet: &[u8], mut offset: usize, count: usize) -> Option<usize> {
    for _ in 0..count {
        offset = skip_name(packet, offset, true)?;
        let rdlength = read_u16(packet, offset + 8)? as usize;
        offset = offset.checked_add(10)?.checked_add(rdlength)?;
        packet.get(..offset)?;
    }
    Some(offset)
}

/// Strictly parse a single-question outbound DNS packet.
pub(crate) fn parse_query(packet: &[u8]) -> Option<ParsedQuery> {
    if packet.len() < 12 {
        return None;
    }
    let flags = read_u16(packet, 2)?;
    let qdcount = read_u16(packet, 4)?;
    // Query (QR=0), standard opcode, exactly one question.
    if flags & 0x8000 != 0 || flags & 0x7800 != 0 || flags & 0x0040 != 0 || qdcount != 1 {
        return None;
    }
    let (domain, offset) = parse_name(packet, 12, false)?;
    let qtype = read_u16(packet, offset)?;
    let qclass = read_u16(packet, offset + 2)?;
    if qclass != 1 {
        return None;
    }
    let record_count = (read_u16(packet, 6)? as usize)
        .checked_add(read_u16(packet, 8)? as usize)?
        .checked_add(read_u16(packet, 10)? as usize)?;
    let question_end = offset.checked_add(4)?;
    if skip_resource_records(packet, question_end, record_count)? != packet.len() {
        return None;
    }
    Some(ParsedQuery {
        id: read_u16(packet, 0)?,
        domain,
        qtype,
        query_type: qtype_to_string(qtype),
    })
}

/// Return whether a parsed response belongs to `query`.
///
/// Transaction IDs alone are not sufficient: clients may reuse an ID while
/// multiple questions are outstanding. Match the complete question tuple and
/// compare names case-insensitively, as DNS names are case-insensitive.
pub(crate) fn response_matches_query(query: &ParsedQuery, response: &ParsedResponse) -> bool {
    query.id == response.id
        && query.qtype == response.qtype
        && query.domain.eq_ignore_ascii_case(&response.domain)
}

/// Parse `packet` as a response and require an exact transaction/question
/// match with `query`.
pub(crate) fn parse_matching_response(
    packet: &[u8],
    query: &ParsedQuery,
) -> Option<ParsedResponse> {
    let response = parse_response(packet)?;
    response_matches_query(query, &response).then_some(response)
}

/// Build a DNS error response which preserves only a valid original question.
///
/// For a malformed query, a minimal header carrying the transaction ID (when
/// present) is returned. For a valid query, the exact question bytes are
/// echoed. Answer, authority and additional counts are always zero, so no
/// unvalidated bytes are reflected as records.
pub(crate) fn build_error_response(query: &[u8], code: DnsErrorCode) -> Vec<u8> {
    let mut response = vec![0u8; 12];
    if let Some(id) = query.get(..2) {
        response[..2].copy_from_slice(id);
    }

    let request_flags = read_u16(query, 2).unwrap_or_default();
    // Preserve the opcode, RD and CD bits. Set QR and the requested RCODE;
    // AA/TC/RA/AD/Z are deliberately clear because this proxy is not an
    // authoritative or recursive resolver itself.
    let flags = 0x8000 | (request_flags & 0x7910) | code as u16;
    response[2..4].copy_from_slice(&flags.to_be_bytes());

    if parse_query(query).is_some() {
        if let Some((_, name_end)) = parse_name(query, 12, false) {
            if let Some(question_end) = name_end.checked_add(4) {
                if let Some(question) = query.get(12..question_end) {
                    response[4..6].copy_from_slice(&1u16.to_be_bytes());
                    response.extend_from_slice(question);
                }
            }
        }
    }
    response
}

pub(crate) fn build_formerr_response(query: &[u8]) -> Vec<u8> {
    build_error_response(query, DnsErrorCode::FormErr)
}

pub(crate) fn build_servfail_response(query: &[u8]) -> Vec<u8> {
    build_error_response(query, DnsErrorCode::ServFail)
}

pub(crate) fn build_refused_response(query: &[u8]) -> Vec<u8> {
    build_error_response(query, DnsErrorCode::Refused)
}

/// Parse A and AAAA resource records from a DNS response packet.
///
/// Extracts IP addresses from answer section records. Only parses
/// type A (1) and AAAA (28) records. Returns an empty vec on any
/// parse failure.
#[cfg(test)]
pub(crate) fn parse_response_ips(packet: &[u8]) -> Vec<IpAddr> {
    parse_response(packet)
        .map(|response| {
            response
                .answers
                .into_iter()
                .map(|answer| answer.ip)
                .collect()
        })
        .unwrap_or_default()
}

/// Parse a response and retain only A/AAAA records reachable from the
/// question through zero or more CNAME records.
pub(crate) fn parse_response(packet: &[u8]) -> Option<ParsedResponse> {
    if packet.len() < 12 {
        return None;
    }
    let flags = read_u16(packet, 2)?;
    let qdcount = read_u16(packet, 4)? as usize;
    let ancount = read_u16(packet, 6)? as usize;
    let nscount = read_u16(packet, 8)? as usize;
    let arcount = read_u16(packet, 10)? as usize;
    if flags & 0x8000 == 0 || flags & 0x7800 != 0 || flags & 0x0040 != 0 || qdcount != 1 {
        return None;
    }

    let (domain, mut offset) = parse_name(packet, 12, true)?;
    let qtype = read_u16(packet, offset)?;
    if read_u16(packet, offset + 2)? != 1 {
        return None;
    }
    offset += 4;
    if flags & 0x0200 != 0 {
        offset = skip_resource_records(packet, offset, ancount + nscount + arcount)?;
        if offset != packet.len() {
            return None;
        }
        return Some(ParsedResponse {
            id: read_u16(packet, 0)?,
            domain,
            qtype,
            answers: Vec::new(),
        });
    }
    if flags & 0x000F != 0 {
        offset = skip_resource_records(packet, offset, ancount + nscount + arcount)?;
        if offset != packet.len() {
            return None;
        }
        return Some(ParsedResponse {
            id: read_u16(packet, 0)?,
            domain,
            qtype,
            answers: Vec::new(),
        });
    }

    let mut cnames: HashMap<String, (String, u32)> = HashMap::new();
    let mut addresses: HashMap<String, Vec<(IpAddr, u32)>> = HashMap::new();
    for _ in 0..ancount {
        let (owner, next) = parse_name(packet, offset, true)?;
        let owner = owner.to_ascii_lowercase();
        offset = next;
        let rtype = read_u16(packet, offset)?;
        let class = read_u16(packet, offset + 2)?;
        let ttl = read_u32(packet, offset + 4)?;
        let rdlength = read_u16(packet, offset + 8)? as usize;
        offset += 10;
        let rdata_end = offset.checked_add(rdlength)?;
        packet.get(offset..rdata_end)?;

        if class == 1 {
            match rtype {
                1 if rdlength == 4 => {
                    let bytes = packet.get(offset..offset + 4)?;
                    addresses.entry(owner).or_default().push((
                        IpAddr::V4(Ipv4Addr::new(bytes[0], bytes[1], bytes[2], bytes[3])),
                        ttl,
                    ));
                }
                28 if rdlength == 16 => {
                    let octets: [u8; 16] = packet.get(offset..offset + 16)?.try_into().ok()?;
                    addresses
                        .entry(owner)
                        .or_default()
                        .push((IpAddr::V6(Ipv6Addr::from(octets)), ttl));
                }
                5 => {
                    let (target, consumed) = parse_name(packet, offset, true)?;
                    if consumed != rdata_end {
                        return None;
                    }
                    cnames.insert(owner, (target.to_ascii_lowercase(), ttl));
                }
                _ => {}
            }
        }
        offset = rdata_end;
    }
    offset = skip_resource_records(packet, offset, nscount + arcount)?;
    if offset != packet.len() {
        return None;
    }

    let mut current = domain.to_ascii_lowercase();
    let mut chain_ttl = u32::MAX;
    let mut seen = HashSet::new();
    for _ in 0..32 {
        if !seen.insert(current.clone()) {
            return None;
        }
        if let Some(records) = addresses.get(&current) {
            let answers = records
                .iter()
                .map(|(ip, ttl)| DnsAnswer {
                    ip: *ip,
                    ttl: Duration::from_secs((*ttl).min(chain_ttl) as u64),
                })
                .collect();
            return Some(ParsedResponse {
                id: read_u16(packet, 0)?,
                domain,
                qtype,
                answers,
            });
        }
        let Some((target, ttl)) = cnames.get(&current) else {
            return Some(ParsedResponse {
                id: read_u16(packet, 0)?,
                domain,
                qtype,
                answers: Vec::new(),
            });
        };
        chain_ttl = chain_ttl.min(*ttl);
        current = target.clone();
    }
    None
}

// ---------------------------------------------------------------------------
// DNS wire format parsing
// ---------------------------------------------------------------------------

/// Parse the QNAME and QTYPE from a DNS wire-format query.
///
/// DNS wire format (RFC 1035 §4.1):
/// - 12-byte header
/// - Question section: sequence of length-prefixed labels (QNAME),
///   followed by 2-byte QTYPE and 2-byte QCLASS.
///
/// Returns `(domain, query_type)` or `None` if parsing fails.
pub fn parse_qname(packet: &[u8]) -> Option<(String, String)> {
    let flags = read_u16(packet, 2)?;
    if flags & 0x8000 != 0 {
        parse_response(packet).map(|r| (r.domain, qtype_to_string(r.qtype)))
    } else {
        parse_query(packet).map(|q| (q.domain, q.query_type))
    }
}

/// Convert a DNS QTYPE number to a human-readable string.
fn qtype_to_string(qtype: u16) -> String {
    match qtype {
        1 => "A".to_string(),
        2 => "NS".to_string(),
        5 => "CNAME".to_string(),
        6 => "SOA".to_string(),
        12 => "PTR".to_string(),
        15 => "MX".to_string(),
        16 => "TXT".to_string(),
        28 => "AAAA".to_string(),
        33 => "SRV".to_string(),
        255 => "ANY".to_string(),
        other => format!("TYPE{other}"),
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// Build a minimal DNS query packet for testing.
    fn build_dns_query(domain: &str, qtype: u16) -> Vec<u8> {
        let mut packet = Vec::new();

        // Header (12 bytes): ID=0x1234, flags=0x0100 (standard query, RD=1)
        packet.extend_from_slice(&[0x12, 0x34, 0x01, 0x00]);
        // QDCOUNT=1, ANCOUNT=0, NSCOUNT=0, ARCOUNT=0
        packet.extend_from_slice(&[0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]);

        // Question section: QNAME as length-prefixed labels
        for label in domain.split('.') {
            packet.push(label.len() as u8);
            packet.extend_from_slice(label.as_bytes());
        }
        packet.push(0x00); // Root label terminator

        // QTYPE and QCLASS=IN(1)
        packet.extend_from_slice(&qtype.to_be_bytes());
        packet.extend_from_slice(&[0x00, 0x01]);

        packet
    }

    #[test]
    fn parse_simple_a_query() {
        let packet = build_dns_query("example.com", 1);
        let parsed = parse_query(&packet).unwrap();
        assert_eq!(parsed.id, 0x1234);
        assert_eq!(parsed.qtype, 1);
        let (domain, qtype) = parse_qname(&packet).unwrap();
        assert_eq!(domain, "example.com");
        assert_eq!(qtype, "A");
    }

    #[test]
    fn parse_aaaa_query() {
        let packet = build_dns_query("ipv6.example.com", 28);
        let (domain, qtype) = parse_qname(&packet).unwrap();
        assert_eq!(domain, "ipv6.example.com");
        assert_eq!(qtype, "AAAA");
    }

    #[test]
    fn parse_subdomain_exfil_pattern() {
        let packet = build_dns_query("AKIA1234ABCD.leak.attacker.com", 1);
        let (domain, _) = parse_qname(&packet).unwrap();
        assert_eq!(domain, "AKIA1234ABCD.leak.attacker.com");
    }

    #[test]
    fn parse_txt_query() {
        let packet = build_dns_query("_dmarc.example.com", 16);
        let (domain, qtype) = parse_qname(&packet).unwrap();
        assert_eq!(domain, "_dmarc.example.com");
        assert_eq!(qtype, "TXT");
    }

    #[test]
    fn parse_single_label() {
        let packet = build_dns_query("localhost", 1);
        let (domain, qtype) = parse_qname(&packet).unwrap();
        assert_eq!(domain, "localhost");
        assert_eq!(qtype, "A");
    }

    #[test]
    fn parse_short_packet_returns_none() {
        let short = vec![0u8; 5];
        assert!(parse_qname(&short).is_none());
    }

    #[test]
    fn malformed_queries_fail_closed_parser() {
        let mut compressed = build_dns_query("example.com", 1);
        compressed[12] = 0xC0;
        compressed[13] = 0x0C;
        assert!(parse_query(&compressed).is_none());

        let mut oversized_label = build_dns_query("example.com", 1);
        oversized_label[12] = 64;
        assert!(parse_query(&oversized_label).is_none());

        let mut truncated = build_dns_query("example.com", 1);
        truncated.truncate(15);
        assert!(parse_query(&truncated).is_none());

        let mut response_flag = build_dns_query("example.com", 1);
        response_flag[2] |= 0x80;
        assert!(parse_query(&response_flag).is_none());

        let mut trailing_garbage = build_dns_query("example.com", 1);
        trailing_garbage.extend_from_slice(&[0xDE, 0xAD]);
        assert!(parse_query(&trailing_garbage).is_none());
    }

    #[test]
    fn edns_query_is_structurally_validated() {
        let mut packet = build_dns_query("example.com", 1);
        packet[10..12].copy_from_slice(&1u16.to_be_bytes());
        // Root owner, OPT type, 1232-byte UDP payload, no options.
        packet.extend_from_slice(&[0, 0, 41, 4, 208, 0, 0, 0, 0, 0, 0]);
        assert!(parse_query(&packet).is_some());

        packet.pop();
        assert!(parse_query(&packet).is_none());
    }

    #[test]
    fn generated_error_response_preserves_safe_query_metadata() {
        let mut packet = build_dns_query("blocked.example", 28);
        packet[2..4].copy_from_slice(&0x0110u16.to_be_bytes());
        let response = build_refused_response(&packet);

        assert_eq!(&response[..2], &packet[..2]);
        assert_eq!(
            u16::from_be_bytes(response[2..4].try_into().unwrap()),
            0x8115
        );
        assert_eq!(u16::from_be_bytes(response[4..6].try_into().unwrap()), 1);
        assert_eq!(&response[12..], &packet[12..]);
        assert_eq!(&response[6..12], &[0; 6]);
    }

    #[test]
    fn malformed_error_response_is_a_bounded_header_only_formerr() {
        let response = build_formerr_response(&[0xCA, 0xFE, 0x7F]);
        assert_eq!(response.len(), 12);
        assert_eq!(&response[..2], &[0xCA, 0xFE]);
        assert_eq!(response[3] & 0x0f, DnsErrorCode::FormErr as u8);
        assert_eq!(&response[4..], &[0; 8]);
    }

    #[test]
    fn parse_empty_qname_returns_none() {
        // Header + immediate root label (no actual labels)
        let mut packet = vec![0u8; 12];
        packet.push(0x00); // empty QNAME
        assert!(parse_qname(&packet).is_none());
    }

    /// Build a minimal DNS response with A record answers. Mirrors the wire
    /// shape a real resolver returns (the reply echoes the question, so the
    /// in-line recvfrom-exit path recovers the domain from the response).
    fn build_dns_response(domain: &str, ips: &[Ipv4Addr]) -> Vec<u8> {
        let mut packet = Vec::new();

        // Header: ID=0x1234, flags=0x8180 (response, RD=1, RA=1)
        packet.extend_from_slice(&[0x12, 0x34, 0x81, 0x80]);
        // QDCOUNT=1, ANCOUNT=N, NSCOUNT=0, ARCOUNT=0
        packet.extend_from_slice(&[0x00, 0x01]);
        packet.extend_from_slice(&(ips.len() as u16).to_be_bytes());
        packet.extend_from_slice(&[0x00, 0x00, 0x00, 0x00]);

        // Question section
        for label in domain.split('.') {
            packet.push(label.len() as u8);
            packet.extend_from_slice(label.as_bytes());
        }
        packet.push(0x00);
        packet.extend_from_slice(&[0x00, 0x01, 0x00, 0x01]); // QTYPE=A, QCLASS=IN

        // Answer section — each answer uses a compression pointer to the QNAME
        for ip in ips {
            packet.extend_from_slice(&[0xC0, 0x0C]); // Name pointer to offset 12
            packet.extend_from_slice(&[0x00, 0x01]); // TYPE=A
            packet.extend_from_slice(&[0x00, 0x01]); // CLASS=IN
            packet.extend_from_slice(&[0x00, 0x00, 0x01, 0x2C]); // TTL=300
            packet.extend_from_slice(&[0x00, 0x04]); // RDLENGTH=4
            packet.extend_from_slice(&ip.octets());
        }

        packet
    }

    #[test]
    fn parse_response_extracts_a_records() {
        let response = build_dns_response(
            "example.com",
            &[
                Ipv4Addr::new(142, 250, 80, 46),
                Ipv4Addr::new(142, 250, 80, 47),
            ],
        );
        let ips = parse_response_ips(&response);
        assert_eq!(ips.len(), 2);
        assert_eq!(ips[0], IpAddr::V4(Ipv4Addr::new(142, 250, 80, 46)));
        assert_eq!(ips[1], IpAddr::V4(Ipv4Addr::new(142, 250, 80, 47)));
    }

    #[test]
    fn matching_response_requires_id_name_type_and_standard_opcode() {
        let query = build_dns_query("exact.example", 1);
        let parsed_query = parse_query(&query).unwrap();
        let response = build_dns_response("exact.example", &[Ipv4Addr::new(192, 0, 2, 10)]);
        assert!(parse_matching_response(&response, &parsed_query).is_some());

        let mut wrong_id = response.clone();
        wrong_id[1] ^= 1;
        assert!(parse_matching_response(&wrong_id, &parsed_query).is_none());

        let wrong_name = build_dns_response("other.example", &[Ipv4Addr::new(192, 0, 2, 10)]);
        assert!(parse_matching_response(&wrong_name, &parsed_query).is_none());

        let mut wrong_type = response.clone();
        let (_, question_end) = parse_name(&wrong_type, 12, true).unwrap();
        wrong_type[question_end..question_end + 2].copy_from_slice(&28u16.to_be_bytes());
        assert!(parse_matching_response(&wrong_type, &parsed_query).is_none());

        let mut wrong_opcode = response;
        wrong_opcode[2] |= 0x08;
        assert!(parse_matching_response(&wrong_opcode, &parsed_query).is_none());
    }

    #[test]
    fn response_rejects_malformed_trailing_sections_but_accepts_edns() {
        let mut response = build_dns_response("exact.example", &[Ipv4Addr::new(192, 0, 2, 11)]);
        response.extend_from_slice(&[0xDE, 0xAD]);
        assert!(parse_response(&response).is_none());

        response.truncate(response.len() - 2);
        response[10..12].copy_from_slice(&1u16.to_be_bytes());
        response.extend_from_slice(&[0, 0, 41, 4, 208, 0, 0, 0, 0, 0, 0]);
        assert!(parse_response(&response).is_some());

        response.pop();
        assert!(parse_response(&response).is_none());
    }

    #[test]
    fn truncated_response_still_requires_complete_declared_structure() {
        let mut response = build_dns_response("truncated.example", &[Ipv4Addr::new(192, 0, 2, 12)]);
        response[2] |= 0x02;

        let parsed = parse_response(&response).expect("complete truncated response should parse");
        assert!(parsed.answers.is_empty());

        let mut incomplete = response.clone();
        incomplete.pop();
        assert!(parse_response(&incomplete).is_none());

        response.extend_from_slice(&[0xDE, 0xAD]);
        assert!(parse_response(&response).is_none());
    }

    #[test]
    fn parse_response_echoes_qname_for_cache() {
        // The in-line recvfrom-exit path recovers the domain from the response's
        // question section (no query↔response correlation state). Verify a
        // response round-trips through parse_qname.
        let response = build_dns_response("api.anthropic.com", &[Ipv4Addr::new(160, 79, 104, 10)]);
        let (domain, _) = parse_qname(&response).unwrap();
        assert_eq!(domain, "api.anthropic.com");
    }

    #[test]
    fn parse_response_empty_answer() {
        let query = build_dns_query("example.com", 1);
        let ips = parse_response_ips(&query);
        assert!(ips.is_empty());
    }

    #[test]
    fn parse_response_short_packet() {
        let ips = parse_response_ips(&[0u8; 5]);
        assert!(ips.is_empty());
    }

    #[test]
    fn cname_chain_seeds_only_reachable_address_with_bounded_ttl() {
        let mut packet = build_dns_query("alias.example", 1);
        packet[2] = 0x81;
        packet[3] = 0x80;
        packet[6..8].copy_from_slice(&2u16.to_be_bytes());

        // alias.example CNAME target.example, TTL 120
        packet.extend_from_slice(&[0xC0, 0x0C, 0x00, 0x05, 0x00, 0x01]);
        packet.extend_from_slice(&120u32.to_be_bytes());
        let mut target_name = Vec::new();
        target_name.push(6);
        target_name.extend_from_slice(b"target");
        target_name.push(7);
        target_name.extend_from_slice(b"example");
        target_name.push(0);
        packet.extend_from_slice(&(target_name.len() as u16).to_be_bytes());
        packet.extend_from_slice(&target_name);

        // target.example A 192.0.2.44, TTL 300
        packet.extend_from_slice(&target_name);
        packet.extend_from_slice(&[0x00, 0x01, 0x00, 0x01]);
        packet.extend_from_slice(&300u32.to_be_bytes());
        packet.extend_from_slice(&[0x00, 0x04, 192, 0, 2, 44]);

        let parsed = parse_response(&packet).unwrap();
        assert_eq!(parsed.domain, "alias.example");
        assert_eq!(
            parsed.answers,
            vec![DnsAnswer {
                ip: "192.0.2.44".parse().unwrap(),
                ttl: Duration::from_secs(120),
            }]
        );
    }
}
