/**
 * TypeScript types mirroring the Rust API types.
 *
 * AUTO-GENERATED by `scripts/gen-api-types.sh` — do not edit manually.
 * Run that script (or the CI type-drift check) to regenerate after changing
 * any Rust API struct in the `grith-*` crates.
 */

// ---------------------------------------------------------------------------
// Health
// ---------------------------------------------------------------------------

export interface HealthResponse {
  status: "healthy" | "degraded" | "unhealthy";
  version: string;
  uptime_seconds: number;
  subsystems: Record<string, SubsystemStatus>;
}

export interface SubsystemStatus {
  status: "ok" | "degraded" | "error";
  message?: string;
  latency_ms?: number;
}

// ---------------------------------------------------------------------------
// Digest
// ---------------------------------------------------------------------------

export type DigestStatus = "pending" | "approved" | "denied" | "expired" | "escalated";

export type ScoreSeverity = "low" | "medium" | "high" | "critical";

export interface FilterBreakdown {
  filter_name: string;
  score: number;
  rule_id: string;
  message: string;
}

export interface DigestItem {
  id: string;
  created_at: string;
  session_id?: string | null;
  tool_call_type: string;
  arguments_summary: string;
  composite_score: number;
  severity: ScoreSeverity;
  filter_breakdown: FilterBreakdown[];
  task_context: string | null;
  plugin_id: string;
  status: DigestStatus;
  reviewed_at: string | null;
  review_action: string | null;
  reviewer_notes: string | null;
  informational_only: boolean;
  escalated_at: string | null;
  escalated_by: string | null;
}

export interface DigestListResponse {
  items: DigestItem[];
  total: number;
  pending_count: number;
  escalated_count: number;
  limit: number;
  offset: number;
}

export interface DigestActionRequest {
  action: "approve" | "deny" | "learn" | "escalate" | "unlock_egress" | "deny_and_terminate" | "allow_always";
  notes?: string;
}

export type RefreshFailureKind =
  | "transient"
  | "revoked"
  | "unauthorized"
  | "protocol";

export interface RefreshState {
  last_success: string | null;
  last_failure: string | null;
  last_failure_kind: RefreshFailureKind | null;
  last_failure_reason: string | null;
  next_attempt: string | null;
  air_gapped: boolean;
  successes_total: number;
  failures_total: number;
}

export interface TierResponse {
  tier: string;
  seats: number;
  max_sessions: number;
  renewal_date: string | null;
  billing_portal_url: string | null;
  features: Record<string, boolean>;
  refresh: RefreshState | null;
  /** Rolling count of session-limit (429) rejections within the window. */
  session_limit_rejections?: number;
  /** Length of the rejection-count window, in days. */
  session_limit_rejection_window_days?: number;
}

export interface LicenseStatusResponse {
  tier: string;
  seats: number;
  renewal_date: string | null;
  billing_portal_url: string | null;
  air_gapped: boolean;
  hours_since_refresh: number | null;
  refresh: RefreshState;
}

/** GET /api/onboarding/status — non-secret state for the Get-started card. */
export interface OnboardingStatus {
  onboarded: boolean;
  audit_sync: boolean;
  default_provider: string;
  tier: string;
  trial_active: boolean;
  notifications_configured: boolean;
  active_sessions: number;
  dismissed: boolean;
}

// ---------------------------------------------------------------------------
// Audit
// ---------------------------------------------------------------------------

export interface FilterResultSummary {
  filter_name: string;
  matched: boolean;
  score: number;
  rule_id: string;
  severity: string;
  message: string;
}

export type ProxyActionSummary = "allow" | "queue" | "deny";

export type RecordType = "full" | "compact";

export interface AuditRecord {
  id: string;
  timestamp: string;
  session_id: string;
  plugin_id: string;
  tool_call_type: string;
  arguments_summary: string;
  arguments_hash: string;
  composite_score: number;
  proxy_action: ProxyActionSummary;
  filter_results: FilterResultSummary[];
  execution_result: string | null;
  evaluation_time_ms: number;
  task_context: string | null;
  source: string;
  supervised_tool?: string | null;
  supervised_pid?: number | null;
  /// Project name for the session (from --project or the cwd basename),
  /// persisted on the record so audit history can be labelled by project.
  project_name?: string | null;
  correlation_id?: string | null;
  record_hash?: string | null;
  prev_hash?: string | null;
  chain_sequence?: number | null;
  /// "full" — proxy-evaluated row (default). "compact" — short-circuit
  /// bookkeeping row from session-allowed / noise-path paths.
  record_type?: RecordType;
}

export interface AuditListResponse {
  records: AuditRecord[];
  total: number;
  limit?: number;
}

export interface AuditQuery {
  session_id?: string;
  time_from?: string;
  time_to?: string;
  min_score?: number;
  action_filter?: ProxyActionSummary[];
  call_type_filter?: string[];
  limit?: number;
  offset?: number;
  /// `"full"` (default) returns only proxy-decision rows. `"all"`
  /// includes compact short-circuit rows from session-allowed and
  /// noise-path paths.
  include?: "full" | "all";
}

export type AuditExportFormat = "json" | "csv";

export interface ExfilStatsResponse {
  total_blocked: number;
  total_queued: number;
  total_redacted: number;
  by_protocol: Record<string, number>;
  top_blocked_destinations: Array<{ domain: string; count: number }>;
}

// ---------------------------------------------------------------------------
// Proxy
// ---------------------------------------------------------------------------

export interface FilterStatus {
  name: string;
  phase: string;
  enabled: boolean;
  is_ready: boolean;
  evaluation_count: number;
  avg_latency_ms: number;
}

export interface ProxyStatusResponse {
  auto_allow_threshold: number;
  auto_deny_threshold: number;
  total_evaluations: number;
  allow_count: number;
  queue_count: number;
  deny_count: number;
  filters: FilterStatus[];
}

export interface ProxyTestFilterDetail {
  filter_name: string;
  matched: boolean;
  score: number;
  severity: string;
  message: string;
}

export interface ProxyTestResponse {
  composite_score: number;
  action: string;
  decision_reason: string;
  evaluation_time_ms: number;
  filters_evaluated: number;
  filter_results: ProxyTestFilterDetail[];
}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

export interface ConfigScopeInfo {
  local: string;
  team: string;
}

export interface ProxyConfigResponse {
  auto_allow_threshold: number;
  auto_deny_threshold: number;
}

export interface FilterConfigEntry {
  id: string;
  name: string;
  phase: string;
  enabled: boolean;
}

export interface ConfigResponse {
  config_scope: ConfigScopeInfo;
  proxy: ProxyConfigResponse;
  filters: FilterConfigEntry[];
}

export interface ConfigUpdateResponse {
  status: string;
  scope: string;
  filters_updated: number;
  proxy_updated: boolean;
  message: string;
}

// ---------------------------------------------------------------------------
// Supervisor Sessions
// ---------------------------------------------------------------------------

export interface SessionStats {
  total_intercepted: number;
  total_allowed: number;
  total_queued: number;
  total_denied: number;
  total_filtered_noise: number;
}

export interface SessionSummary {
  id: string;
  tool_name: string;
  /** Project name derived from the working directory (e.g., "grith-website"). */
  project_name?: string | null;
  /** Absolute working directory the supervised tool was launched from. */
  cwd?: string | null;
  /** Controlling terminal of the launching CLI (e.g. "pts/21"). */
  tty?: string | null;
  root_pid: number;
  uptime_seconds: number;
  /** Seconds since the last heartbeat/activity — the session's "idle" age. */
  last_activity_seconds?: number;
  stats: SessionStats;
  containment_remaining_seconds?: number | null;
}

export interface SessionDetailResponse {
  id: string;
  tool_name: string;
  root_pid: number;
  uptime_seconds: number;
  process_tree_pids: number[];
  stats: SessionStats;
  containment_remaining_seconds?: number | null;
}

export interface SessionListResponse {
  sessions: SessionSummary[];
  total: number;
}

// ---------------------------------------------------------------------------
// WebSocket Events
// ---------------------------------------------------------------------------

export type WsEventType =
  | "tool_call_started"
  | "tool_call_completed"
  | "proxy_evaluation"
  | "digest_queued"
  | "digest_reviewed"
  | "error";

export interface WsToolCallStarted {
  type: "tool_call_started";
  call_id: string;
  timestamp: string;
  source_id: string;
  tool_call_type: string;
  arguments_summary: string;
}

export interface WsToolCallCompleted {
  type: "tool_call_completed";
  call_id: string;
  timestamp: string;
  result: string;
  duration_ms: number;
}

export interface WsProxyEvaluation {
  type: "proxy_evaluation";
  call_id: string;
  /** Supervisor session id the evaluation belongs to. */
  session_id?: string;
  timestamp: string;
  composite_score: number;
  action: ProxyActionSummary;
  evaluation_time_ms: number;
  filter_results: FilterResultSummary[];
  /** The tool call type, e.g. "FileRead(/home/...)" or "NetConnect(api.anthropic.com)". */
  call_type?: string;
  /** The supervised tool name, e.g. "claude-code". */
  tool_name?: string;
  /** Project name for the session (cwd basename or --project override), so a
   *  brand-new session's rows can be labelled without waiting for the audit poll. */
  project_name?: string | null;
  /** Human-readable reason for the decision. */
  reason?: string;
}

export interface WsDigestQueued {
  type: "digest_queued";
  item_id: string;
  timestamp: string;
  tool_call_type: string;
  composite_score: number;
}

export interface WsDigestReviewed {
  type: "digest_reviewed";
  item_id: string;
  timestamp: string;
  action: "approve" | "deny" | "learn" | "escalate";
}

export interface WsError {
  type: "error";
  timestamp: string;
  message: string;
}

export type WsEvent =
  | WsToolCallStarted
  | WsToolCallCompleted
  | WsProxyEvaluation
  | WsDigestQueued
  | WsDigestReviewed
  | WsError;

// ---------------------------------------------------------------------------
// Canary Tokens
// ---------------------------------------------------------------------------

export interface CanaryToken {
  id: string;
  label: string;
  value_prefix: string;
}

export interface CanaryListResponse {
  items: CanaryToken[];
  total: number;
}

export interface CanaryCreateRequest {
  label: string;
  value?: string;
  generate?: boolean;
}

// ---------------------------------------------------------------------------
// Notifications
// ---------------------------------------------------------------------------

export interface ChannelHealth {
  connected: boolean;
  latency_ms?: number;
  error?: string;
}

export interface ChannelInfo {
  id: string;
  display_name: string;
  required_tier: "community" | "pro" | "enterprise";
  supports_interactive: boolean;
  enabled: boolean;
  health: ChannelHealth | null;
}

export interface NotificationEventSent {
  type: "sent";
  item_id: string;
  channel_id: string;
  external_id?: string;
  timestamp: string;
}

export interface NotificationEventDelivered {
  type: "delivered";
  item_id: string;
  channel_id: string;
  timestamp: string;
}

export interface NotificationEventFailed {
  type: "failed";
  item_id: string;
  channel_id: string;
  error: string;
  timestamp: string;
}

export interface NotificationEventInteractiveResponse {
  type: "interactive_response";
  item_id: string;
  channel_id: string;
  action: string;
  reviewer: string;
  timestamp: string;
}

export type NotificationEvent =
  | NotificationEventSent
  | NotificationEventDelivered
  | NotificationEventFailed
  | NotificationEventInteractiveResponse;

// ---------------------------------------------------------------------------
// Adaptive Scoring
// ---------------------------------------------------------------------------

export interface CategoryStats {
  approved: number;
  denied: number;
  approval_rate: number;
}

export interface AdaptiveStatsResponse {
  enabled: boolean;
  total_observations: number;
  categories: Record<string, CategoryStats>;
}

export interface AdaptiveFeedbackRequest {
  tool_type_category: string;
  matched_filters: string[];
  original_score: number;
  outcome: "approved" | "denied";
}

export interface AdaptiveFeedbackResponse {
  status: string;
  total_observations: number;
}

// ---------------------------------------------------------------------------
// Analytics (Pro)
// ---------------------------------------------------------------------------

export interface LatencyPercentiles {
  avg_ms: number;
  p50_ms: number;
  p95_ms: number;
  p99_ms: number;
}

export interface FilterTriggerCount {
  name: string;
  trigger_count: number;
}

export interface AnalyticsTimeRange {
  earliest: string | null;
  latest: string | null;
}

export interface AnalyticsSummaryResponse {
  total_evaluations: number;
  allow_count: number;
  queue_count: number;
  deny_count: number;
  avg_score: number;
  latency: LatencyPercentiles;
  top_filters: FilterTriggerCount[];
  time_range: AnalyticsTimeRange;
}

// ---------------------------------------------------------------------------
// Policies (Enterprise)
// ---------------------------------------------------------------------------

export interface ProxyOverrides {
  auto_allow_threshold?: number;
  auto_deny_threshold?: number;
}

export interface AllowlistConfig {
  paths: string[];
  commands: string[];
  domains: string[];
}

export interface PolicyRules {
  proxy?: ProxyOverrides;
  filters: Record<string, boolean>;
  allowlists?: AllowlistConfig;
}

export interface Policy {
  name: string;
  description: string;
  version: number;
  created_at: string;
  updated_at: string;
  rules: PolicyRules;
}

export interface PolicyListResponse {
  policies: Policy[];
  total: number;
}

// ---------------------------------------------------------------------------
// PR 4 Phase G — Session-pinned binary inventory
// ---------------------------------------------------------------------------

export interface InventoryEntry {
  /** Canonical absolute path of the pinned binary. */
  path: string;
  /** Hex-encoded SHA-256 of the binary contents at session start. */
  sha256: string;
}

export interface InventoryResponse {
  session_id: string;
  binaries_pinned: number;
  total_scanned: number;
  /** True when the walk hit INVENTORY_MAX_FILES and stopped short. */
  truncated: boolean;
  entries: InventoryEntry[];
  /**
   * Cross-session diff. Currently always omitted — populated by a
   * future PR once last-N inventories persist to the audit DB.
   */
  previous_session_diff?: unknown;
}

// ---------------------------------------------------------------------------
// PR 5 Phase E — Listener rewrites
// ---------------------------------------------------------------------------

export interface ListenerRewrite {
  /** Audit record UUID. */
  id: string;
  /** RFC3339 timestamp. */
  timestamp: string;
  /** Supervised tracee PID. */
  pid?: number;
  /** Tool name (e.g. "codex"). */
  tool?: string;
  /** Original address:port the tracee asked for. */
  original_addr: string;
  /** Address:port the kernel actually bound after the clamp. */
  rewritten_addr: string;
  /** Description of the local_listener_policy entry that authorised this rewrite. */
  clamp_profile_entry: string;
}

export interface ListenerRewritesResponse {
  session_id: string;
  total: number;
  rewrites: ListenerRewrite[];
}
