// SPDX-License-Identifier: MPL-2.0
// Copyright (c) grith contributors

//! Event types for the TUI event loop. Three Tokio tasks communicate via channels.

use crate::tui::state::{Decision, FilterHit, SessionStats};

/// Events generated by the agent / proxy engine.
#[derive(Debug, Clone)]
pub enum AgentEvent {
    /// Streaming text chunk from the agent.
    TextChunk { text: String, dim: bool },

    /// Agent is about to make a tool call.
    ToolCallStart { name: String, args: String },

    /// Proxy has evaluated the call.
    Decision {
        name: String,
        args: String,
        decision: Decision,
    },

    /// Agent resumed after a queued call was approved.
    Resumed,

    /// Session ended.
    Complete(SessionStats),

    /// Cost update from LLM response.
    CostUpdate { cost_delta: f64 },

    /// Token usage update.
    TokenUpdate {
        prompt_tokens: u64,
        completion_tokens: u64,
    },

    /// Error from agent loop.
    Error(String),

    /// Raw output line from supervised tool.
    ToolOutput(String),
}

/// Events from the TUI to the main agent/supervisor thread.
#[derive(Debug, Clone)]
pub enum TuiInput {
    /// User submitted a prompt.
    Prompt(String),
    /// User requested quit.
    Quit,
}

/// Events generated by the supervisor wrapping an external tool.
#[derive(Debug, Clone)]
pub enum SupervisorEvent {
    /// Raw stdout line from the wrapped tool.
    ToolOutputLine(String),

    /// Wrapped process exited.
    ProcessExited { code: i32 },
}

/// Internal TUI events (keyboard, resize, tick).
#[derive(Debug, Clone)]
pub enum TuiEvent {
    /// Keyboard input.
    Key(crossterm::event::KeyEvent),
    /// Terminal resized.
    Resize(u16, u16),
    /// Timer tick for animations (live dot, cursor blink).
    Tick,
}

/// Format an intercept detail string from a decision.
pub fn format_intercept_detail(decision: &Decision) -> String {
    match decision {
        Decision::Allow => "allowed".to_string(),
        Decision::Queue { score, filters } | Decision::Deny { score, filters } => {
            let filter_parts: Vec<String> = filters
                .iter()
                .filter(|f| f.delta.abs() > 0.0)
                .map(|f| format!("{} {:+.1}", f.name, f.delta))
                .collect();
            format!(
                "{}  \u{00b7} score {:.1}",
                filter_parts.join(" \u{00b7} "),
                score
            )
        }
    }
}

/// Convert a proxy `EvalResult`-style score and filter list into our TUI `Decision` type.
pub fn score_to_tui_decision(score: f64, filters: Vec<FilterHit>) -> Decision {
    if score < 3.0 {
        Decision::Allow
    } else if score <= 8.0 {
        Decision::Queue {
            score: score as f32,
            filters,
        }
    } else {
        Decision::Deny {
            score: score as f32,
            filters,
        }
    }
}

/// Strip ANSI escape sequences from raw PTY output bytes.
/// Returns clean text lines suitable for display in the output panel.
pub fn strip_ansi_and_split_lines(raw: &[u8]) -> Vec<String> {
    let mut clean = Vec::with_capacity(raw.len());
    let mut i = 0;
    while i < raw.len() {
        if raw[i] == 0x1b {
            i += 1;
            if i < raw.len() && raw[i] == b'[' {
                i += 1;
                // CSI sequence: skip params and intermediates until final byte
                while i < raw.len() && (0x20..=0x3f).contains(&raw[i]) {
                    i += 1;
                }
                if i < raw.len() && (0x40..=0x7e).contains(&raw[i]) {
                    i += 1;
                }
            } else if i < raw.len() && raw[i] == b']' {
                // OSC sequence: skip until ST (BEL or ESC\)
                i += 1;
                while i < raw.len() && raw[i] != 0x07 {
                    if raw[i] == 0x1b && i + 1 < raw.len() && raw[i + 1] == b'\\' {
                        i += 2;
                        break;
                    }
                    i += 1;
                }
                if i < raw.len() && raw[i] == 0x07 {
                    i += 1;
                }
            }
        } else if raw[i] == b'\r' {
            // Skip carriage returns
            i += 1;
        } else {
            clean.push(raw[i]);
            i += 1;
        }
    }

    let text = String::from_utf8_lossy(&clean);
    text.split('\n')
        .filter(|line| !line.is_empty())
        .map(|s| s.to_string())
        .collect()
}

/// Split raw PTY output into lines, preserving ANSI escape sequences for color rendering.
/// Strips only carriage returns and OSC/cursor-movement sequences that don't affect color.
pub fn split_lines_preserve_ansi(raw: &[u8]) -> Vec<String> {
    let mut out = Vec::with_capacity(raw.len());
    let mut i = 0;
    while i < raw.len() {
        if raw[i] == 0x1b {
            // Check what follows ESC
            if i + 1 < raw.len() && raw[i + 1] == b']' {
                // OSC sequence — strip entirely (window titles, etc.)
                i += 2;
                while i < raw.len() && raw[i] != 0x07 {
                    if raw[i] == 0x1b && i + 1 < raw.len() && raw[i + 1] == b'\\' {
                        i += 2;
                        break;
                    }
                    i += 1;
                }
                if i < raw.len() && raw[i] == 0x07 {
                    i += 1;
                }
            } else if i + 1 < raw.len() && raw[i + 1] == b'[' {
                // CSI sequence — check if it's SGR (ends with 'm')
                let start = i;
                i += 2;
                while i < raw.len() && (0x20..=0x3f).contains(&raw[i]) {
                    i += 1;
                }
                if i < raw.len() && (0x40..=0x7e).contains(&raw[i]) {
                    let final_byte = raw[i];
                    i += 1;
                    if final_byte == b'm' {
                        // SGR — preserve color/style codes
                        out.extend_from_slice(&raw[start..i]);
                    }
                    // Non-SGR CSI (cursor movement, erase, etc.) — strip
                }
            } else {
                // Other ESC sequence — strip
                i += 1;
                if i < raw.len() {
                    i += 1;
                }
            }
        } else if raw[i] == b'\r' {
            i += 1;
        } else {
            out.push(raw[i]);
            i += 1;
        }
    }

    let text = String::from_utf8_lossy(&out);
    text.split('\n')
        .filter(|line| !line.is_empty())
        .map(|s| s.to_string())
        .collect()
}

/// Parse a string containing ANSI SGR escape sequences into ratatui `Span`s.
pub fn ansi_to_spans(input: &str) -> Vec<ratatui::text::Span<'static>> {
    use ratatui::style::Style;
    use ratatui::text::Span;

    let mut spans = Vec::new();
    let mut current_style = Style::default();
    let mut text_buf = String::new();
    let bytes = input.as_bytes();
    let mut i = 0;

    while i < bytes.len() {
        if bytes[i] == 0x1b && i + 1 < bytes.len() && bytes[i + 1] == b'[' {
            // Flush accumulated text
            if !text_buf.is_empty() {
                spans.push(Span::styled(std::mem::take(&mut text_buf), current_style));
            }
            // Parse CSI SGR sequence
            i += 2;
            let mut params = Vec::new();
            let mut num = String::new();
            while i < bytes.len() && (0x20..=0x3f).contains(&bytes[i]) {
                if bytes[i] == b';' {
                    params.push(num.parse::<u8>().unwrap_or(0));
                    num.clear();
                } else {
                    num.push(bytes[i] as char);
                }
                i += 1;
            }
            if !num.is_empty() {
                params.push(num.parse::<u8>().unwrap_or(0));
            }
            if i < bytes.len() && bytes[i] == b'm' {
                i += 1;
                current_style = apply_sgr_params(&params, current_style);
            } else if i < bytes.len() {
                i += 1; // skip unknown final byte
            }
        } else {
            text_buf.push(bytes[i] as char);
            i += 1;
        }
    }
    if !text_buf.is_empty() {
        spans.push(Span::styled(text_buf, current_style));
    }
    spans
}

fn apply_sgr_params(params: &[u8], mut style: ratatui::style::Style) -> ratatui::style::Style {
    use ratatui::style::{Color, Modifier};

    let mut i = 0;
    if params.is_empty() {
        return ratatui::style::Style::default();
    }
    while i < params.len() {
        match params[i] {
            0 => style = ratatui::style::Style::default(),
            1 => style = style.add_modifier(Modifier::BOLD),
            2 => style = style.add_modifier(Modifier::DIM),
            3 => style = style.add_modifier(Modifier::ITALIC),
            4 => style = style.add_modifier(Modifier::UNDERLINED),
            7 => style = style.add_modifier(Modifier::REVERSED),
            22 => style = style.remove_modifier(Modifier::BOLD | Modifier::DIM),
            23 => style = style.remove_modifier(Modifier::ITALIC),
            24 => style = style.remove_modifier(Modifier::UNDERLINED),
            27 => style = style.remove_modifier(Modifier::REVERSED),
            // Standard foreground colors
            30 => style = style.fg(Color::Black),
            31 => style = style.fg(Color::Red),
            32 => style = style.fg(Color::Green),
            33 => style = style.fg(Color::Yellow),
            34 => style = style.fg(Color::Blue),
            35 => style = style.fg(Color::Magenta),
            36 => style = style.fg(Color::Cyan),
            37 => style = style.fg(Color::White),
            38 => {
                // Extended foreground: 38;5;N or 38;2;R;G;B
                if i + 1 < params.len() && params[i + 1] == 5 && i + 2 < params.len() {
                    style = style.fg(Color::Indexed(params[i + 2]));
                    i += 2;
                } else if i + 1 < params.len() && params[i + 1] == 2 && i + 4 < params.len() {
                    style = style.fg(Color::Rgb(params[i + 2], params[i + 3], params[i + 4]));
                    i += 4;
                }
            }
            39 => style = style.fg(Color::Reset),
            // Standard background colors
            40 => style = style.bg(Color::Black),
            41 => style = style.bg(Color::Red),
            42 => style = style.bg(Color::Green),
            43 => style = style.bg(Color::Yellow),
            44 => style = style.bg(Color::Blue),
            45 => style = style.bg(Color::Magenta),
            46 => style = style.bg(Color::Cyan),
            47 => style = style.bg(Color::White),
            48 => {
                // Extended background: 48;5;N or 48;2;R;G;B
                if i + 1 < params.len() && params[i + 1] == 5 && i + 2 < params.len() {
                    style = style.bg(Color::Indexed(params[i + 2]));
                    i += 2;
                } else if i + 1 < params.len() && params[i + 1] == 2 && i + 4 < params.len() {
                    style = style.bg(Color::Rgb(params[i + 2], params[i + 3], params[i + 4]));
                    i += 4;
                }
            }
            49 => style = style.bg(Color::Reset),
            // Bright foreground colors
            90..=97 => style = style.fg(Color::Indexed(params[i] - 90 + 8)),
            // Bright background colors
            100..=107 => style = style.bg(Color::Indexed(params[i] - 100 + 8)),
            _ => {}
        }
        i += 1;
    }
    style
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_format_intercept_detail_allow() {
        assert_eq!(format_intercept_detail(&Decision::Allow), "allowed");
    }

    #[test]
    fn test_format_intercept_detail_queue() {
        let decision = Decision::Queue {
            score: 4.1,
            filters: vec![
                FilterHit {
                    name: "cmd_structure".to_string(),
                    delta: 1.5,
                },
                FilterHit {
                    name: "dest_reputation".to_string(),
                    delta: 2.6,
                },
            ],
        };
        let detail = format_intercept_detail(&decision);
        assert!(detail.contains("cmd_structure +1.5"));
        assert!(detail.contains("dest_reputation +2.6"));
        assert!(detail.contains("score 4.1"));
    }

    #[test]
    fn test_format_intercept_detail_deny() {
        let decision = Decision::Deny {
            score: 9.2,
            filters: vec![FilterHit {
                name: "path_match".to_string(),
                delta: 5.0,
            }],
        };
        let detail = format_intercept_detail(&decision);
        assert!(detail.contains("path_match +5.0"));
        assert!(detail.contains("score 9.2"));
    }

    #[test]
    fn test_score_to_tui_decision() {
        assert!(matches!(
            score_to_tui_decision(1.0, vec![]),
            Decision::Allow
        ));
        assert!(matches!(
            score_to_tui_decision(5.0, vec![]),
            Decision::Queue { .. }
        ));
        assert!(matches!(
            score_to_tui_decision(9.0, vec![]),
            Decision::Deny { .. }
        ));
    }

    #[test]
    fn test_format_filters_zero_delta_excluded() {
        let decision = Decision::Queue {
            score: 3.5,
            filters: vec![
                FilterHit {
                    name: "active".to_string(),
                    delta: 2.0,
                },
                FilterHit {
                    name: "zero".to_string(),
                    delta: 0.0,
                },
            ],
        };
        let detail = format_intercept_detail(&decision);
        assert!(detail.contains("active"));
        assert!(!detail.contains("zero"));
    }

    #[test]
    fn test_strip_ansi_plain_text() {
        let input = b"hello world\n";
        let lines = strip_ansi_and_split_lines(input);
        assert_eq!(lines, vec!["hello world"]);
    }

    #[test]
    fn test_strip_ansi_color_codes() {
        let input = b"\x1b[32mgreen\x1b[0m normal";
        let lines = strip_ansi_and_split_lines(input);
        assert_eq!(lines, vec!["green normal"]);
    }

    #[test]
    fn test_strip_ansi_cursor_movement() {
        let input = b"\x1b[2J\x1b[Hline one\nline two\n";
        let lines = strip_ansi_and_split_lines(input);
        assert_eq!(lines, vec!["line one", "line two"]);
    }

    #[test]
    fn test_strip_ansi_carriage_return() {
        let input = b"overwritten\rfinal\n";
        let lines = strip_ansi_and_split_lines(input);
        assert_eq!(lines, vec!["overwrittenfinal"]);
    }

    #[test]
    fn test_strip_ansi_empty() {
        let lines = strip_ansi_and_split_lines(b"");
        assert!(lines.is_empty());
    }

    #[test]
    fn test_strip_ansi_osc_sequence() {
        let input = b"\x1b]0;window title\x07actual text\n";
        let lines = strip_ansi_and_split_lines(input);
        assert_eq!(lines, vec!["actual text"]);
    }
}
